# Generated by Django 5.1.7 on 2025-03-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(choices=[('La Dorada', 'La Dorada'), ('Honda', 'Honda'), ('Mariquita', 'Mariquita')], max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('puntuacion', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
